### ISSUE TITLE
Using uuid format in parametesr

### ISSUE THREAD

**Issue by sah4ez** [google/oatts#16]
In my specification I using parameters:
```
        - in: header
          name: My-Header
          schema:
            type: string
            format: uuid
```
And for this format I got an error:
```
$ sudo oatts generate -s ./openapi.yaml -w ./tests/
Error: unknown generator for "uuid" in /
    at generate (/usr/local/lib/node_modules/oatts/node_modules/json-schema-faker/lib/jsf.js:74:13)
    at Parameter.getSample (/usr/local/lib/node_modules/oatts/node_modules/sway/lib/types/parameter.js:94:39)
    at /usr/local/lib/node_modules/oatts/lib/process.js:275:90
    at Array.forEach (<anonymous>)
    at processParams (/usr/local/lib/node_modules/oatts/lib/process.js:259:24)
    at /usr/local/lib/node_modules/oatts/lib/process.js:202:22
    at Array.forEach (<anonymous>)
    at processTransactions (/usr/local/lib/node_modules/oatts/lib/process.js:196:29)
    at /usr/local/lib/node_modules/oat
```
